Add dependency not found detection

diff --git a/sman b/sman
--- a/sman
+++ b/sman
@@ -1,6 +1,15 @@
 #!/bin/sh
 # depends on: groff, gnu eqn, zcat, some pager
 
+err() {
+    echo "$@"
+    exit 1
+}
+
+command -v groff || err "groff not found"
+command -v eqn || err "eqn not found, you might want to install groff"
+command -v zcat || err "zcat not found, you might want to install gzip"
+
 for pager in "$MANPAGER" "$PAGER" 'less' 'more'; do
     if [ -n "$pager" ]; then
         manpager="$pager"
